<!-- SPDX-License-Identifier: GPL-2.0-or-later -->
<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <OutputType>Exe</OutputType>
    <AssemblyName>StationEngine</AssemblyName>
    <RootNamespace>Zeus.StationEngine</RootNamespace>
    <ServerGarbageCollection>false</ServerGarbageCollection>
    <ConcurrentGarbageCollection>true</ConcurrentGarbageCollection>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Station.Engine.Hosting\Station.Engine.Hosting.csproj" />
    <ProjectReference Include="..\Zeus.Plugins.Host\Zeus.Plugins.Host.csproj" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Zeus.Server.Tests" />
  </ItemGroup>

</Project>
