// SPDX-License-Identifier: GPL-2.0-or-later
//
// Zeus — OpenHPSDR Protocol-1 / Protocol-2 client.
// Copyright (C) 2025-2026 Douglas J. Cerrato (KB2UKA),
//                         Christian Suarez (N9WAR), and contributors.
//
// Zeus is distributed WITHOUT ANY WARRANTY; see the GNU General Public
// License for details.
//
// GENERATED — the ZeusMidiCommand enum, the UI catalogue, and the dispatch
// switch are produced from one shared command table so the three never drift.
// Full Thetis-parity command surface (PureSignal arm DELIBERATELY excluded).

namespace Zeus.Contracts;

/// <summary>Every Thetis MIDI/controller command Zeus exposes for mapping.
/// Append-only: never reorder or remove a value. Saved bindings persist the
/// command as this enum's <b>numeric ordinal</b> — <c>MidiConfigStore</c>
/// serializes the binding document with default System.Text.Json (no
/// <c>JsonStringEnumConverter</c>), which writes enums as their integer index.
/// Reordering or removing a value therefore silently remaps every operator's
/// stored bindings to the wrong command, so ordinal stability is load-bearing.
/// (The REST/learn pipeline does add the string-enum converter, so on-the-wire
/// DTOs use names; only the LiteDB blob is ordinal-keyed.) <c>Supported</c>
/// commands route to a real Zeus seam; the rest are parity-only placeholders
/// selectable in the UI that log a Debug no-op. PureSignal arm is intentionally
/// absent from this surface.</summary>
public enum ZeusMidiCommand
{
    VfoAtoB,
    VfoBtoA,
    VfoSwap,
    RitOnOff,
    XitOnOff,
    RIT_clear,
    XIT_clear,
    RIT_inc,
    XIT_inc,
    BandUp,
    BandDown,
    Band160m,
    Band80m,
    Band60m,
    Band40m,
    Band30m,
    Band20m,
    Band17m,
    Band15m,
    Band12m,
    Band10m,
    Band6m,
    Band2m,
    Band160mRX2,
    Band80mRX2,
    Band60mRX2,
    Band40mRX2,
    Band30mRX2,
    Band20mRX2,
    Band17mRX2,
    Band15mRX2,
    Band12mRX2,
    Band10mRX2,
    Band6mRX2,
    Band2mRX2,
    Rx2BandUp,
    Rx2BandDown,
    ChangeFreqVfoA,
    ChangeFreqVfoB,
    TuningStepUp,
    TuningStepDown,
    MoveVFOADown100Khz,
    MoveVFOAUp100Khz,
    MoveVFOBDown100Khz,
    MoveVFOBUp100Khz,
    CTunOnOff,
    RX2CTunOnOff,
    LockVFOOnOff,
    LockVFOAOnOff,
    LockVFOBOnOff,
    VfoSyncOnOff,
    MultiStepVfoA,
    SwapVFOWheels,
    ToggleVFOWheel,
    Rx1ModeNext,
    Rx1ModePrev,
    Rx2ModeNext,
    Rx2ModePrev,
    ModeSSB,
    ModeLSB,
    ModeUSB,
    ModeDSB,
    ModeCW,
    ModeCWL,
    ModeCWU,
    ModeFM,
    ModeAM,
    ModeDIGU,
    ModeSPEC,
    ModeDIGL,
    ModeSAM,
    ModeDRM,
    Rx1FilterWider,
    Rx1FilterNarrower,
    Rx2FilterWider,
    Rx2FilterNarrower,
    FilterHigh,
    FilterLow,
    FilterShift,
    FilterBandwidth,
    TxFilterHigh,
    TxFilterLow,
    ApfOnOff,
    ApfFreq,
    ApfBandwidth,
    ApfGain,
    ApfTypeDoublePole,
    ApfTypeMatched,
    ApfTypeGaussian,
    ApfTypeBiquad,
    AgcModeUp,
    AgcModeDown,
    Rx2AgcModeUp,
    Rx2AgcModeDown,
    AgcModeKnob,
    Rx2AgcModeKnob,
    Rx1AgcLevel,
    Rx2AgcLevel,
    Rx1AgcLevelInc,
    Rx2AgcLevelInc,
    Nr1OnOff,
    Nr2OnOff,
    Nr3OnOff,
    Nr4OnOff,
    Nr4Amount,
    Rx2Nr1OnOff,
    Rx2Nr2OnOff,
    Rx2Nr3OnOff,
    Rx2Nr4OnOff,
    Rx2Nr4Amount,
    Rx1Nb1OnOff,
    Rx1Nb2OnOff,
    Rx2Nb1OnOff,
    Rx2Nb2OnOff,
    AutoNotchOnOff,
    Rx2AutoNotchOnOff,
    SpectralNbOnOff,
    Rx2SpectralNbOnOff,
    SquelchOnOff,
    SquelchLevel,
    Rx2SquelchOnOff,
    Rx2SquelchLevel,
    BinauralOnOff,
    Rx1AutoAgc,
    Rx2AutoAgc,
    SetAfGain,
    VolumeVfoA,
    VolumeVfoB,
    VolumeVfoAIncr,
    VolumeVfoBIncr,
    Rx2Volume,
    MuteOnOff,
    Rx2MuteOnOff,
    MonOnOff,
    MicGain,
    PreAmpSettingsKnob,
    TxAfMonitor,
    VacOnOff,
    Vac2OnOff,
    IqToVac,
    IqToVacRx2,
    VacGainRx,
    VacGainTx,
    Vac2GainRx,
    Vac2GainTx,
    PanCenter,
    PanSlider,
    PanSliderInc,
    RatioMainSubRx,
    Rx2Pan,
    AudioAmpOnOff,
    MoxOnOff,
    TunOnOff,
    VoxOnOff,
    DriveLevel,
    DriveLevelInc,
    TunPowerLevel,
    DexpOnOff,
    DexpThreshold,
    CompanderOnOff,
    RxEqOnOff,
    TxEqOnOff,
    TwoToneOnOff,
    ExternalPaOnOff,
    TunerOnOff,
    TunerBypassOnOff,
    SplitOnOff,
    QuickSplitOnOff,
    QuickSplitAndSplitOnOff,
    ToggleTx,
    CpdrLevel,
    VoxGain,
    CwSpeed,
    CwSpeedInc,
    CwBreakIn,
    CwQsk,
    CwxMacro1,
    CwxMacro2,
    CwxMacro3,
    CwxMacro4,
    CwxMacro5,
    CwxMacro6,
    CwxMacro7,
    CwxMacro8,
    CwxMacro9,
    CwxStop,
    CwxKey,
    CwxPtt,
    StartOnOff,
    CloseConsole,
    ZoomInc,
    ZoomDec,
    ZoomSliderInc,
    ZoomSliderFix,
    DisplayAverage,
    DisplayPeak,
    DisplayTxFilter,
    DisplayModeNext,
    DisplayModePrev,
    WaterfallLowLimit,
    WaterfallHighLimit,
    MultiRxOnOff,
    RX2OnOff,
    Rx2PreAmpOnOff,
    DiversityEnable,
    DiversityPhase,
    DiversityGain,
    DiversityReference,
    DiversitySource,
    DiversityFormOpen,
    ZeroBeatPress,
    QuickModeSave,
    QuickModeRestore,
    QuickPlayOnOff,
    QuickRecOnOff,
    ZoomToBandStore,
    ZoomToBandRecall,
    MidiMessagesPerTuneStepUp,
    MidiMessagesPerTuneStepDown,
    MidiMessagesPerTuneStepToggle,
    ESCFormOnOff,
    D100hChangeFreqVfoA,
}
